### ISSUE TITLE
xml bounding box exceeds image boundary

### ISSUE THREAD

**Issue by liangxi627** [JosephKJ/SDD-Utils#1]
I got the following warning when I creating lmdb file, how to solve it? Please help me, thanks~
> W0425 16:45:53.220152 24499 io.cpp:334]/home/stanford_campus_dataset/scd/Annotations/hyang_video0_1924.xml bounding box exceeds image boundary

**Comment by ZhihongChen123** [comment]
Hello.Did you solve the problem?I have some problems running the code，Please help me, thank you very much @liangxi627

**Comment by liangxi627** [comment]
Yes, I solved it, there are indeed some labels exceed hte image boundary in the original annotation files, so   I modify the code to filter the wrong labels.
