### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by ZhihongChen123** [JosephKJ/SDD-Utils#2]
When I run annotate.py there is an error: CalledProcessError: Command 'ffmpeg -i D:\czh\SDD-Utils-master\SDD-Utils-master\StanfordDroneDataset\videos\gates\video0\video.mov gates_video0_%d.jpg' returned non-zero exit status 1.please help me ,thank you very much!

**Comment by pranavpawar3** [comment]
I have faced the exact same issue. Can you please tell me how to deal with this?

**Comment by pranavpawar3** [comment]
@JosephKJ Can you please help in this issue, I have been trying debugging from past 2 days, But still I am getting the same error
`/media/pranav/New: No such file or directory
Traceback (most recent call last):
  File "annotate.py", line 271, in <module>
    split_and_annotate(num_training_images, num_val_images, num_testing_images)
  File "annotate.py", line 201, in split_and_annotate
    split_video(video_file, image_name_prefix)
  File "annotate.py", line 46, in split_video
    return subprocess.check_output('ffmpeg -i ' + os.path.abspath(video_file) + ' '+ image_name_prefix +'%d.jpg', shell=True, cwd=os.path.join(destination_path, 'JPEGImages'))
  File "/opt/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'ffmpeg -i /media/pranav/New Volume1/StanfordDroneDataset/videos/bookstore/video1/video.mov bookstore_video1_%d.jpg' returned non-zero exit status 1.

`

**Comment by JosephKJ** [comment]
Hi Pranav,

`/media/pranav/New: No such file or directory`

rename your `New Volume1` to `New_Volume1` and try.

**Comment by pranavpawar3** [comment]
Thanks @JosephKJ The issue got solved after changing the name. 
This was the major bottleneck I was facing for my model training. 
Thanks again

**Comment by JosephKJ** [comment]
The issue comes when the path to the input video is wrong. Closing the same.
